# Generated by Django 2.0.3 on 2018-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(help_text='Enter a book genre (e.g. English,Kiswahili,Germany,Spanish etc.)', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.ManyToManyField(help_text='Select a language for this book', to='catalog.Language'),
        ),
    ]
